Repository one-acre-fund/oaf--ph-ee-operations-app, pull requests merged in 2023-09, with the labels that each got.

#8 Feature/transactions filter for asterisk
  src/main/java/org/apache/fineract/api/OperationsDetailedApi.java
  src/test/java/org/apache/fineract/test/OperationsDetailedApiTest.java
Labels: size/L

#9 Ensure the exported csv contains accurate data - SER-1926
  RELEASE_NOTES.md
  src/main/java/org/apache/fineract/api/OperationsDetailedApi.java
Labels: size/S

#6 SER-1822 - audit setup
  RELEASE_NOTES.md
  src/main/java/org/apache/fineract/api/AuditApiResource.java
  src/main/java/org/apache/fineract/audit/data/AuditSearch.java
  src/main/java/org/apache/fineract/audit/data/AuditSource.java
  src/main/java/org/apache/fineract/audit/data/AuditSourceRepository.java
  src/main/java/org/apache/fineract/audit/events/AuditEventListener.java
  src/main/java/org/apache/fineract/audit/events/NewAuditEvent.java
  src/main/java/org/apache/fineract/audit/service/AuditService.java
  src/main/java/org/apache/fineract/audit/service/AuditServiceImpl.java
  src/main/java/org/apache/fineract/audit/specs/AuditSpec.java
  src/main/java/org/apache/fineract/audit/specs/BaseSpecification.java
  src/main/java/org/apache/fineract/utils/DateUtil.java
  src/main/resources/application.yml
  src/main/resources/sql/migrations/tenant/V44__create_audit_table.sql
  src/test/java/org/apache/fineract/test/AuditServiceTest.java
  src/test/java/org/apache/fineract/test/AuditSpecTest.java
Labels: size/XL
